import 'gitalk/dist/gitalk.css'
import Gitalk from 'gitalk'

/**
 * Each page should create new instance for generate id correctly.
 * So export a function to create new Gitalk instance on each call.
 * To get current URL(with hash) correctly as id.
 * And to use it as blew:
 *
 * gitalk().render('gitalk-container')
 */
export default () =>
  new Gitalk({
    // ------------------------------------------------------
    clientID: 'de47adf4f9d0394257eb',
    clientSecret: '7619f44e8a16d8d6b450a588caf2e087f1fb8500',
    // these two is GENERATED BY GITHUB
    // ------------------------------------------------------
    // Repo for store comments as issues
    repo: 'comments',
    // Username of github
    owner: 'zfanli',
    // Array of admins, username of github
    admin: ['zfanli'],
    // Ensure uniqueness and length less than 50
    id: `vue-training/${location.hash}`,
    // Facebook-like distraction free mode
    // Just open a mask upon others when comment box is focusing
    distractionFreeMode: true,
  })
